baseURL: 'https://pakeypay.github.io/'
languageCode: 'zh-ch'
title: '宁少'
theme: "PaperMod"
hasCJKLanguage: true
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs: true
canonifyURLs: true

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

disableRSS: false
disableSitemap: false

pygmentsStyle: "monokai"
pygmentsUseClasses: false

minify:
  disableXML: true
  minifyOutput: true

taxonomies:
  # tag: tags
  series: series
  category: categories

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: '宁少'
  description: "不想写代码的设计师不是一个好产品经理"
  keywords: [博客,blog, 独立博客 , 宁少 ,设计师]
  author: 宁少
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2006/01/02"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowWordCount: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  comments: true
	#twikoo:
  #  version: 1.5.10 // 这个版本号要自己手动修改，和twikoo的版本号要对得上
  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "images/favicon64.ico"
    favicon16x16: "images/favicon16.ico"
    favicon32x32: "images/favicon32.ico"
  #   apple_touch_icon: "<link / abs url>"
  #   safari_pinned_tab: "<link / abs url>"

  label:
    text: "宁少"
    # icon: /apple-touch-icon.png
    iconHeight: 35

  # home-info mode
  homeInfoParams:
    Title: "Hi！"
    Content: "我是宁！曾在阿里做设计，分享职场和生活的感悟在这。若你觉着有意思，加我微信：pakeypay。"

  # socialIcons:
   #  - name: twitter
  #     url: "https://weibo.com/shaoning001"
  #   - name: wechat
  #     url: "https://stackoverflow.com"
  #   - name: github
  #     url: "https://github.com/"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: [博客,blog, 宁少, 设计师,互联网]

  baiduAnalytics:
    url: https://hm.baidu.com/hm.js?d49ee6f85b43e02f356ca3b9d04d1e7f
 
menu:
  main:
#    - identifier: series
#      name: 系列文章
#      url: /series/
#      weight: 1

#    - identifier: categories
#      name: 分类
#      url: /categories/
#      weight: 2

#    - identifier: tags
#      name: 标签
#      url: /tags/
#      weight: 10
    
#     - identifier: archives
#       name: 归档
#       url: /archives/
#       weight: 3
      - name: Archive
        url: archives
        weight: 5
      - name: Search
        url: search/
        weight: 10
      - name: Tags
        url: tags/
        weight: 10
      - name: Categories
        url: categories/
        weight: 10